### Step 1: Import necessary libraries

In [35]:
import pandas as pd
import numpy as np

### Step 2: Load the Data

In [36]:
cafe_sales = pd.read_csv("E:\IEEE-CS-DataScience-26\Task_15\cafe_sales.csv")

<>:1: SyntaxWarning: invalid escape sequence '\I'
<>:1: SyntaxWarning: invalid escape sequence '\I'
C:\Users\salmaa\AppData\Local\Temp\ipykernel_39300\2895553514.py:1: SyntaxWarning: invalid escape sequence '\I'
  cafe_sales = pd.read_csv("E:\IEEE-CS-DataScience-26\Task_15\cafe_sales.csv")

In [37]:
cafe_sales

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

### Step 3: Explore the Data

##### display the first 10 rows to see the "messy" data

In [38]:
cafe_sales.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

##### check how many rows and columns

In [39]:
cafe_sales.shape

(10000, 8)

##### display basic info about the dataset to identify nulls and incorrect data types

In [40]:
cafe_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

##### check unique values for `Item`, `Payment Method`, and `Location`

In [41]:
cafe_sales['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [42]:
cafe_sales['Payment Method'].unique()

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan],
      dtype=object)

In [43]:
cafe_sales['Location'].unique()

array(['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR'], dtype=object)

##### check missing values

In [44]:
cafe_sales.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

### Step 4: Handle Missing Values

##### Use `.replace()` to convert "UNKNOWN" and "ERROR" to np.nan

In [45]:
cafe_sales.replace(["UNKNOWN", "ERROR"], np.nan, inplace=True)

In [46]:
cafe_sales['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', nan, 'Sandwich',
       'Juice', 'Tea'], dtype=object)

In [47]:
cafe_sales['Payment Method'].unique()

array(['Credit Card', 'Cash', nan, 'Digital Wallet'], dtype=object)

In [48]:
cafe_sales['Location'].unique()

array(['Takeaway', 'In-store', nan], dtype=object)

In [49]:
cafe_sales.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

### Step 5:Text Sanitization

##### remove hidden spaces from all string columns

In [50]:
for col in cafe_sales.select_dtypes(include='object').columns:
    cafe_sales[col] = cafe_sales[col].str.strip()

##### convert all Item names to lowercase for consistency

In [51]:
cafe_sales['Item'] = cafe_sales['Item'].str.lower()

In [52]:
cafe_sales['Item']

0         coffee
1           cake
2         cookie
3          salad
4         coffee
          ...
9995      coffee
9996         NaN
9997      coffee
9998      cookie
9999    sandwich
Name: Item, Length: 10000, dtype: object

##### use a dictionary to fix any typos in item names if they exist

In [53]:
# array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', nan, 'Sandwich', 'Juice', 'Tea'], dtype=object)

### Step 6: Fix Data Types
##### fix incorrect data types (Quantity, Price Per Unit, Total Spent .....)

In [54]:
cafe_sales['Quantity'] = pd.to_numeric(cafe_sales['Quantity'])

In [55]:
cafe_sales['Price Per Unit'] = pd.to_numeric(cafe_sales['Price Per Unit'])

In [56]:
cafe_sales['Total Spent'] = pd.to_numeric(cafe_sales['Total Spent'])

In [57]:
cafe_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9031 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   float64
 4   Total Spent       9498 non-null   float64
 5   Payment Method    6822 non-null   object
 6   Location          6039 non-null   object
 7   Transaction Date  9540 non-null   object
dtypes: float64(3), object(5)
memory usage: 625.1+ KB

##### identify and fix rows where Quantity might be zero or negative

In [58]:
cafe_sales.loc[cafe_sales['Quantity'] <= 0, 'Quantity'] = np.nan

In [59]:
cafe_sales['Quantity']

0       2.0
1       4.0
2       4.0
3       2.0
4       2.0
       ...
9995    2.0
9996    3.0
9997    4.0
9998    3.0
9999    3.0
Name: Quantity, Length: 10000, dtype: float64

### Step 7: Handle Missing Values (Part 2: Fill NaNs)

##### fill missing `Price Per Unit`

In [60]:
cafe_sales['Price Per Unit']

0       2.0
1       3.0
2       1.0
3       5.0
4       2.0
       ...
9995    2.0
9996    NaN
9997    2.0
9998    NaN
9999    4.0
Name: Price Per Unit, Length: 10000, dtype: float64

In [61]:
cafe_sales['Price Per Unit'].fillna(cafe_sales['Price Per Unit'].median(), inplace=True)

In [62]:
cafe_sales['Price Per Unit']

0       2.0
1       3.0
2       1.0
3       5.0
4       2.0
       ...
9995    2.0
9996    3.0
9997    2.0
9998    3.0
9999    4.0
Name: Price Per Unit, Length: 10000, dtype: float64

##### handle other missing values appropriately (like Payment Method or Location)

In [63]:
cafe_sales['Payment Method'].fillna('unknown', inplace=True)

C:\Users\salmaa\AppData\Local\Temp\ipykernel_39300\3047213448.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cafe_sales['Payment Method'].fillna('unknown', inplace=True)

In [64]:
cafe_sales['Location'].fillna('unknown', inplace=True)

C:\Users\salmaa\AppData\Local\Temp\ipykernel_39300\3542353146.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cafe_sales['Location'].fillna('unknown', inplace=True)

### Step 8: Logical Validation

##### create a new column `Expected_Total` by multiplying `Quantity * Price Per Unit`

In [65]:
cafe_sales['Expected_Total'] = cafe_sales['Quantity'] * cafe_sales['Price Per Unit']

In [66]:
cafe_sales['Expected_Total']

0        4.0
1       12.0
2        4.0
3       10.0
4        4.0
        ...
9995     4.0
9996     9.0
9997     8.0
9998     9.0
9999    12.0
Name: Expected_Total, Length: 10000, dtype: float64

##### filter rows where Total Spent is NOT equal to Expected_Total

In [67]:
filtered = cafe_sales[cafe_sales['Total Spent'] != cafe_sales['Expected_Total']]

In [68]:
filtered

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Expected_Total
2,TXN_4271903,cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19,4.0
20,TXN_3522028,smoothie,NaN,4.0,20.0,Cash,In-store,2023-04-04,NaN
25,TXN_7958992,smoothie,3.0,4.0,NaN,unknown,unknown,2023-12-13,12.0
31,TXN_8927252,NaN,2.0,1.0,NaN,Credit Card,unknown,2023-11-06,2.0
42,TXN_6650263,tea,2.0,1.5,NaN,unknown,Takeaway,2023-01-10,3.0
...,...,...,...,...,...,...,...,...,...
9984,TXN_3142496,smoothie,NaN,4.0,4.0,Cash,Takeaway,2023-07-27,NaN
9988,TXN_9594133,cake,5.0,3.0,NaN,unknown,unknown,NaN,15.0
9993,TXN_4766549,smoothie,2.0,4.0,NaN,Cash,unknown,2023-10-20,8.0
9996,TXN_9659401,NaN,3.0,3.0,3.0,Digital Wallet,unknown,2023-06-02,9.0
9998,TXN_7695629,cookie,3.0,3.0,3.0,Digital Wallet,unknown,2023-12-02,9.0

##### fill missing or incorrect Total Spent values using the Expected_Total calculation.

In [69]:
cafe_sales['Total Spent'] = cafe_sales['Expected_Total']

### Step 9: Handle Dates

##### convert Transaction Date to datetime

In [70]:
cafe_sales['Transaction Date'] = pd.to_datetime(cafe_sales['Transaction Date'])

In [71]:
cafe_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9031 non-null   object
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       9521 non-null   float64
 5   Payment Method    10000 non-null  object
 6   Location          10000 non-null  object
 7   Transaction Date  9540 non-null   datetime64[ns]
 8   Expected_Total    9521 non-null   float64
dtypes: datetime64[ns](1), float64(4), object(4)
memory usage: 703.3+ KB

##### identify transactions with dates in the future (if any) and handle them

In [72]:
from datetime import datetime

today = pd.Timestamp(datetime.today())
cafe_sales.loc[cafe_sales['Transaction Date'] > today, 'Transaction Date'] = np.nan

##### extract "Year" and "Month" into separate columns for analysis

In [73]:
cafe_sales['Year'] = cafe_sales['Transaction Date'].dt.year
cafe_sales['Month'] = cafe_sales['Transaction Date'].dt.month

In [74]:
cafe_sales['Year']

0       2023.0
1       2023.0
2       2023.0
3       2023.0
4       2023.0
         ...
9995    2023.0
9996    2023.0
9997    2023.0
9998    2023.0
9999    2023.0
Name: Year, Length: 10000, dtype: float64

In [75]:
cafe_sales['Month']

0        9.0
1        5.0
2        7.0
3        4.0
4        6.0
        ...
9995     8.0
9996     6.0
9997     3.0
9998    12.0
9999    11.0
Name: Month, Length: 10000, dtype: float64

### Step 10: Remove Duplicates

##### check for duplicates

In [76]:
cafe_sales.duplicated().sum()

np.int64(0)

##### drop duplicates if found

In [79]:
# no duplicate