Step 1. Import the necessary libraries

In [50]:
import pandas as pd

Step 2. Import the dataset & Assign it to a variable called chipo.

In [51]:
chipo = pd.read_csv(r"E:\IEEE-CS-DataScience-26\Task_13\chipotle.csv")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

Step 4. See the first 10 entries

In [52]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

Step 5. What is the number of columns in the dataset?

In [53]:
len(chipo.columns)

5

Step 6. Print a summary of the DataFrame

In [54]:
chipo.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

Step 7. Print the name of all the columns.

In [55]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

Step 8.Display only the item_name column.

In [56]:
chipo['item_name']

0                Chips and Fresh Tomato Salsa
1                                        Izze
2                            Nantucket Nectar
3       Chips and Tomatillo-Green Chili Salsa
4                                Chicken Bowl
                        ...
4617                            Steak Burrito
4618                            Steak Burrito
4619                       Chicken Salad Bowl
4620                       Chicken Salad Bowl
4621                       Chicken Salad Bowl
Name: item_name, Length: 4622, dtype: object

Step 9. Use .loc to display the first 5 rows for only two columns: item_name and item_price

In [57]:
chipo.loc[:4,['item_name','item_price']]

                               item_name item_price
0           Chips and Fresh Tomato Salsa     $2.39
1                                   Izze     $3.39
2                       Nantucket Nectar     $3.39
3  Chips and Tomatillo-Green Chili Salsa     $2.39
4                           Chicken Bowl    $16.98

Step 10. Sort by the name of the item

In [58]:
chipo = chipo.sort_values(by="item_name")

Step 11. Which was the most-ordered item?

Step 12. For the most-ordered item, how many items were ordered?

In [59]:
chipo['item_name'].value_counts().head(1)

item_name
Chicken Bowl    726
Name: count, dtype: int64

Step 13. What was the most ordered item in the choice_description column?

In [60]:
chipo['choice_description'].value_counts().head(1)

choice_description
[Diet Coke]    134
Name: count, dtype: int64

Step 14. How many items were orderd in total?

In [61]:
chipo['quantity'].sum()

np.int64(4972)

Step 15. Retrieve all orders where the item_name is exactly 'Chicken Bowl'

In [62]:
chipo[chipo['item_name'] == 'Chicken Bowl']

,order_id,quantity,item_name,choice_description,item_price
4555,1811,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
1796,726,1,Chicken Bowl,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.49
371,161,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
1759,710,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
2548,1010,1,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Black...",$8.49
...,...,...,...,...,...
2940,1169,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
798,328,1,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$10.98
3700,1483,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
1001,411,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$8.49

Step 16. Find all orders where the quantity is greater than 2.

In [63]:
chipo[chipo['quantity'] > 2]

,order_id,quantity,item_name,choice_description,item_price
2441,970,5,Bottled Water,NaN,$7.50
1425,577,4,Bottled Water,NaN,$6.00
3599,1443,7,Bottled Water,NaN,$10.50
2823,1121,3,Bottled Water,NaN,$3.27
4137,1655,3,Bottled Water,NaN,$4.50
3294,1321,3,Bottled Water,NaN,$4.50
1880,759,4,Bottled Water,NaN,$6.00
4152,1660,10,Bottled Water,NaN,$15.00
3314,1328,3,Bottled Water,NaN,$4.50
4186,1671,3,Bottled Water,NaN,$4.50
818,338,3,Bottled Water,NaN,$3.27
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
2235,901,4,Canned Soda,[Sprite],$4.36
3128,1247,3,Canned Soft Drink,[Diet Coke],$3.75
3089,1231,3,Canned Soft Drink,[Diet Coke],$3.75
917,379,3,Canned Soft Drink,[Lemonade],$3.75
3973,1592,4,Canned Soft Drink,[Coke],$5.00
4098,1642,3,Canned Soft Drink,[Diet Coke],$3.75
850,350,3,Canned Soft Drink,[Sprite],$3.75
1559,633,3,Canned Soft Drink,[Coke],$3.75
689,284,3,Canned Soft Drink,[Diet Coke],$3.75
4490,1786,4,Canned Soft Drink,[Coke],$5.00
4491,1786,4,Canned Soft Drink,[Sprite],$5.00
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25
1514,616,3,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$26.25
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00
3636,1454,3,Chicken Burrito,"[Fresh Tomato Salsa, Rice]",$26.25
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00
3634,1454,3,Chicken Burrito,[Fresh Tomato Salsa],$26.25
2936,1167,3,Chips,NaN,$6.45
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25
1257,511,4,Chips and Fresh Tomato Salsa,NaN,$11.80
2645,1051,3,Chips and Guacamole,NaN,$13.35
4489,1786,4,Chips and Guacamole,NaN,$17.80
2972,1182,3,Chips and Tomatillo-Red Chili Salsa,NaN,$7.17
3270,1309,3,Chips and Tomatillo-Red Chili Salsa,NaN,$7.17
3887,1559,8,Side of Chips,NaN,$13.52
2944,1170,3,Side of Chips,NaN,$5.07
3334,1336,3,Steak Bowl,"[Tomatillo Green Chili (Medium), [Rice, Black ...",$26.07
3603,1443,3,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$27.75
1255,511,3,Steak Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$27.75
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75

Step 17. How many products cost more than $10.00?

In [64]:
# first we need to convert to numeric
chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)
# choosing
chipo[chipo['item_price'] >= 10.00]

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
4485,1786,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.75
3017,1200,1,Barbacoa Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.75
1383,562,1,Barbacoa Bowl,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",11.48
3025,1203,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
...,...,...,...,...,...
496,207,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",11.25
4109,1646,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25

Step 18.Set the order_id column as the index of your DataFrame.

In [65]:
chipo = chipo.set_index('order_id')

In [66]:
chipo

,quantity,item_name,choice_description,item_price
order_id,,,,
1360,2,6 Pack Soft Drink,[Diet Coke],12.98
148,1,6 Pack Soft Drink,[Diet Coke],6.49
749,1,6 Pack Soft Drink,[Coke],6.49
754,1,6 Pack Soft Drink,[Diet Coke],6.49
1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...
948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

18.a. Display the first 5 rows to see how the new index looks.

In [67]:
chipo.head()

          quantity          item_name choice_description  item_price
order_id
1360             2  6 Pack Soft Drink        [Diet Coke]       12.98
148              1  6 Pack Soft Drink        [Diet Coke]        6.49
749              1  6 Pack Soft Drink             [Coke]        6.49
754              1  6 Pack Soft Drink        [Diet Coke]        6.49
1076             1  6 Pack Soft Drink             [Coke]        6.49

18.b. Reset the index back to the default integer index.

In [68]:
chipo = chipo.reset_index()

Step 19. Rename the column item_name to product_name.

In [71]:
chipo = chipo = chipo.rename(columns={'item_name':'product_name'})

Step 20. Convert all text in the choice_description column to lowercase letters.

In [72]:
chipo['choice_description'] = chipo['choice_description'].str.lower()

In [73]:
chipo

,order_id,quantity,product_name,choice_description,item_price
0,1360,2,6 Pack Soft Drink,[diet coke],12.98
1,148,1,6 Pack Soft Drink,[diet coke],6.49
2,749,1,6 Pack Soft Drink,[coke],6.49
3,754,1,6 Pack Soft Drink,[diet coke],6.49
4,1076,1,6 Pack Soft Drink,[coke],6.49
...,...,...,...,...,...
4617,948,1,Veggie Soft Tacos,"[roasted chili corn salsa, [fajita vegetables,...",8.75
4618,322,1,Veggie Soft Tacos,"[fresh tomato salsa, [black beans, cheese, sou...",8.75
4619,1132,1,Veggie Soft Tacos,"[roasted chili corn salsa (medium), [black bea...",8.49
4620,688,1,Veggie Soft Tacos,"[fresh tomato salsa, [fajita vegetables, rice,...",11.25
4621,567,1,Veggie Soft Tacos,"[fresh tomato salsa (mild), [pinto beans, rice...",8.49

Step 21. Create a new column called is_expensive and set it to True if the price is above 12, and False otherwise.

In [75]:
chipo['is_expensive'] = chipo['item_price'] > 12
chipo

,order_id,quantity,product_name,choice_description,item_price,is_expensive
0,1360,2,6 Pack Soft Drink,[diet coke],12.98,True
1,148,1,6 Pack Soft Drink,[diet coke],6.49,False
2,749,1,6 Pack Soft Drink,[coke],6.49,False
3,754,1,6 Pack Soft Drink,[diet coke],6.49,False
4,1076,1,6 Pack Soft Drink,[coke],6.49,False
...,...,...,...,...,...,...
4617,948,1,Veggie Soft Tacos,"[roasted chili corn salsa, [fajita vegetables,...",8.75,False
4618,322,1,Veggie Soft Tacos,"[fresh tomato salsa, [black beans, cheese, sou...",8.75,False
4619,1132,1,Veggie Soft Tacos,"[roasted chili corn salsa (medium), [black bea...",8.49,False
4620,688,1,Veggie Soft Tacos,"[fresh tomato salsa, [fajita vegetables, rice,...",11.25,False
4621,567,1,Veggie Soft Tacos,"[fresh tomato salsa (mild), [pinto beans, rice...",8.49,False

In [76]:
chipo = chipo.drop('choice_description', axis=1)